# Generated by Django 4.0.1 on 2022-01-25 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referral_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralrelationship',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited', to=settings.AUTH_USER_MODEL, verbose_name='invited'),
        ),
        migrations.AddField(
            model_name='referralrelationship',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to=settings.AUTH_USER_MODEL, verbose_name='inviter'),
        ),
        migrations.AddField(
            model_name='referralrelationship',
            name='refer_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral_system.referralcode', verbose_name='referral_code'),
        ),
        migrations.AddField(
            model_name='referralcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='code_master'),
        ),
    ]
